name: validate_gwas_tsv
description: validate gwas tsv
keywords:
  - lncbookv3
  - local
tools:
  - validate_gwas_tsv:
      description: Local lncbookv3-processing module wrapping project scripts or command line tools.
input:
  - meta:
      type: map
      description: Sample or branch metadata.
output:
  - meta:
      type: map
      description: Sample or branch metadata.
authors:
  - lncbookv3-processing
