name: lncbookv3-python
channels:
  - conda-forge
  - bioconda
dependencies:
  - python >=3.10
  - bedtools
  - samtools
  - ucsc-bedtobigbed
  - ucsc-bedgraphtobigwig
  - ucsc-bigbedtobed
  - ucsc-bigwigtobedgraph
  - ucsc-pslmap
  - ucsc-bigwiginfo
  - ucsc-bigbedinfo
