name: make_ucsc_track
description: make ucsc track
keywords:
  - lncbookv3
  - local
tools:
  - make_ucsc_track:
      description: Local lncbookv3-processing module wrapping project scripts or command line tools.
input:
  - meta:
      type: map
      description: Sample or branch metadata.
output:
  - meta:
      type: map
      description: Sample or branch metadata.
authors:
  - lncbookv3-processing
