name: cerna_predict
description: cerna predict
keywords:
  - lncbookv3
  - local
tools:
  - cerna_predict:
      description: Local lncbookv3-processing module wrapping project scripts or command line tools.
input:
  - meta:
      type: map
      description: Sample or branch metadata.
output:
  - meta:
      type: map
      description: Sample or branch metadata.
authors:
  - lncbookv3-processing
